name: Generate Support Team Metric Email

on:
  schedule:
    - cron: '55 12 * * MON'

  workflow_dispatch: # Allows you to manually trigger the workflow from GitHub UI

env:
  ZENDESK_SUBDOMAIN: ${{ secrets.ZENDESK_SUBDOMAIN }}
  ZENDESK_EMAIL: ${{ secrets.ZENDESK_EMAIL }}
  ZENDESK_API_TOKEN: ${{ secrets.ZENDESK_API_TOKEN }}
  RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
  RESEND_AUDIENCE_ID: ${{ secrets.RESEND_AUDIENCE_ID }}
  EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          
jobs:
  zendesk-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas python-dotenv resend

      - name: Run Zendesk Report
        run: |
          python main.py 
